apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: application-client
  name: application-client
  namespace: kafka
spec:
  type: LoadBalancer
  ports:
    - name: "9001"
      port: 9001
      targetPort: 9001
      nodePort: 30090
  selector:
    io.kompose.service: application-client
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: application-client
  name: application-client
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: application-client
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/kafka-docker-ssl-master-kafka: "true"
        io.kompose.service: application-client
    spec:
      containers:
        - env:
            - name: BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: PASSWORD_SASL
              value: "test_secret"
            - name: USER_SASL_NAME
              value: "ckp_tester"
            - name: JAVA_OPTS
              value: -Djavax.net.ssl.trustStore=/application.client.truststore.jks -Djavax.net.ssl.trustStorePassword=changeit -Djavax.net.ssl.keyStore=/application.client.keystore.jks -Djavax.net.ssl.keyStorePassword=changeit
            - name: SCHEMA_REGISTRY_URL
              value: https://schema-registry:8081
            - name: APP_SSL_KEYSTORE_LOCATION
              value: /application.client.keystore.jks
            - name: APP_SSL_KEYSTORE_PASSWORD
              value: "changeit"
            - name: APP_SSL_KEY_PASSWORD
              value: "changeit"
            - name: APP_SSL_TRUSTSTORE_LOCATION
              value: /application.client.truststore.jks
            - name: APP_SSL_TRUSTSTORE_PASSWORD
              value: "changeit"
           
          image: k3d-dev-app-registry:5050/larbotech/app:1.1.27
          name: application-client
          ports:
            - containerPort: 9001
          resources: {}
          volumeMounts:
            - mountPath: /application.client.keystore.jks
              name: ssl-secrets-application-client
              subPath: application.client.keystore.jks
            - mountPath: /application.client.truststore.jks
              name: ssl-secrets-application-client
              subPath: application.client.truststore.jks
      restartPolicy: Always
      volumes:
        - name: ssl-secrets-application-client
          secret:
            secretName: ssl-cert
            items:
              - key: application.client.keystore.jks
                path: application.client.keystore.jks
              - key: application.client.truststore.jks
                path: application.client.truststore.jks
status: {}
