apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      name: "9092"
      targetPort: 9092
    - port: 9094
      name: "9094"
      targetPort: 9094
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      volumes:
        - name: broker-jaas-conf
          configMap:
            name: jaas-conf
            items:
            - key: broker_jaas.conf
              path: broker_jaas.conf
        - name: cert-creds
          configMap:
            name: jaas-conf
            items:
            - key: cert_creds
              path: cert_creds
        - name: ssl-secrets-kafka
          secret:
            secretName: ssl-cert
            items:
            - key: kafka.server.keystore.jks
              path: kafka.server.keystore.jks
            - key: kafka.server.truststore.jks
              path: kafka.server.truststore.jks
      containers:
        - name: kafka
          image: k3d-dev-app-registry:5050/confluentinc/cp-kafka:7.1.0
          env:
            - name: KAFKA_ZOOKEEPER_SASL_ENABLED
              value: "false"
            - name: ZOOKEEPER_SASL_ENABLED
              value: "FALSE"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9094,SASL_SSL://kafka:9092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT, SASL_SSL:SASL_SSL
            - name: KAFKA_OPTS
              value: -Djava.security.auth.login.config=/etc/kafka/secrets/broker_jaas.conf -Dzookeeper.sasl.client=false  #-Dzookeeper.sasl.clientconfig=Client
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_SASL_ENABLED_MECHANISMS
              value: PLAIN
            - name: KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL
              value: PLAIN
            - name: KAFKA_SSL_CLIENT_AUTH
              value: requested
            - name: KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
            - name: KAFKA_LISTENER_NAME_INTERNAL_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
            - name: KAFKA_SSL_KEYSTORE_FILENAME
              value: kafka.server.keystore.jks
            - name: KAFKA_SSL_KEY_CREDENTIALS
              value: cert_creds
            - name: KAFKA_SSL_KEYSTORE_CREDENTIALS
              value: cert_creds
            - name: KAFKA_SSL_TRUSTSTORE_CREDENTIALS
              value: cert_creds
            - name: KAFKA_SSL_TRUSTSTORE_FILENAME
              value: kafka.server.truststore.jks
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL
              value: https://schema-registry:8181
            - name: KAFKA_LOG4J_ROOT_LOGLEVEL
              value: "ERROR"
            - name: KAFKA_LOG4J_LOGGERS
              value: "org.apache.zookeeper=ERROR,org.apache.kafka=ERROR, kafka=ERROR, kafka.cluster=ERROR,kafka.controller=ERROR, kafka.coordinator=ERROR,kafka.log=ERROR,kafka.server=ERROR,kafka.zookeeper=ERROR,state.change.logger=ERROR"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
          ports:
            - containerPort: 9092
            - containerPort: 9094
          volumeMounts:
            - mountPath: /etc/kafka/secrets/broker_jaas.conf
              name: broker-jaas-conf
              subPath: broker_jaas.conf
            - mountPath: /etc/kafka/secrets/cert_creds
              name: cert-creds
              subPath: cert_creds
            - mountPath: /etc/kafka/secrets/kafka.server.keystore.jks
              name: ssl-secrets-kafka
              subPath: kafka.server.keystore.jks
            - mountPath: /etc/kafka/secrets/kafka.server.truststore.jks
              name: ssl-secrets-kafka
              subPath: kafka.server.truststore.jks
